
/**
 * height percent of the list item
 */
export const EIGHT_POINT_TWO_PERCENT: string = '8.2%';

/**
 * with percent of the index component
 */
export const INDEX_COMPONENT_WITH_PERCENT: string = '93.3%';

/**
 * full percent
 */
export const ALL_PERCENT: string = '100%';

/**
 * opacity of text
 */
export const ATTRIBUTE_OPACITY: number = Number.parseFloat('0.6');

/**
 * title font weight
 */
export const TITLE_FONT_WEIGHT: number = 700;

/**
 * common font weight
 */
export const COMMON_FONT_WEIGHT: number = 500;






/**
 * The number of margin ,font size or space
 */
export const enum MARGIN_FONT_SIZE_SPACE {
  COMMON_PADDING = 4,
  COMMON_MARGIN = 8,
  FIRST_MARGIN = 10,
  SECOND_MARGIN = 12,
  THIRD_MARGIN = 14,
  FOURTH_MARGIN = 16,
  FIFTH_MARGIN = 18,
  SIXTH_MARGIN = 20,
  SEVENTH_MARGIN = 24,
  EIGHTH_MARGIN = 28,
  NINTH_MARGIN = 32,
  LAST_MARGIN = 50,
};